---

development:
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/pgns-dev?pool=5' %>

test:
  url: <%= ENV['DATABASE_URL'] ||'postgres://root:root@db/pgns-test?pool=5' %>

production:
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/pgns-prod' %>
